[[reports]]
level = 'Warning'
analyzer = 'UnsafeDataflow:/ReadFlow/CopyFlow/WriteFlow'
description = 'Potential unsafe dataflow issue in `insertion_sort_unsafe`'
location = 'tests/panic_safety/insertion_sort.rs:10:1: 22:2'
source = """
fn insertion_sort_unsafe<T: Ord>(arr: &mut [T]) {
    unsafe {
        for i in 1..arr.len() {
            let item = [0m[31mptr::read(&arr[i])[0m;
            let mut j = i - 1;
            while j >= 0 && [0m[36marr[j] > item[0m {
                j = j - 1;
            }
            [0m[31mptr::copy(&mut arr[j + 1], &mut arr[j + 2], i - j - 1)[0m;
            [0m[33mptr::write(&mut arr[j + 1], item)[0m;
        }
    }
}
[0m"""
