name: Deploy rustc-docs

on:
  push:

env:
  TOOLCHAIN: nightly-2021-10-21

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Rudra API docs
        run: |
          mkdir doc
          # /rudra/index.html
          mv .github/index.html doc

          # no sccache in runner
          rm .cargo -r
          cargo doc --document-private-items --no-deps
          # /rudra/rudra/index.html
          mv target/doc doc/rudra

      - name: Download rustc internal API docs
        run: |
          ls -alh ~/.rustup/toolchains/nightly-2021-10-21-x86_64-unknown-linux-gnu/share/doc/rust/html
          # remove rustc book
          rm ~/.rustup/toolchains/nightly-2021-10-21-x86_64-unknown-linux-gnu/share/doc/rust/html/rustc -r || true
          # download rustc API docs
          rustup component add rustc-docs
          # /rudra/rudra/rustc.html
          mv ~/.rustup/toolchains/nightly-2021-10-21-x86_64-unknown-linux-gnu/share/doc/rust/html/rustc doc/rustc

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: doc

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

